[Desktop Entry]
Name=KWallet PAM Socket Connection
Name[ca]=Connexió a sòcol PAM del KWallet
Name[ca@valencia]=Connexió a sòcol PAM del KWallet
Name[es]=Conexión con el «socket» PAM de KWallet
Name[nl]=KWallet verbinding met PAM-socket
Name[pt]=Ligação por 'Socket' entre PAM e o KWallet
Name[pt_BR]=Conexão do Socket PAM do KWallet
Name[sk]=Pripojenie socketu KWallet PAM
Name[uk]=З’єднання із сокетом PAM KWallet
Name[x-test]=xxKWallet PAM Socket Connectionxx
Comment=Connect to KWallet PAM socket
Comment[ca]=Connecta a un sòcol PAM del KWallet
Comment[ca@valencia]=Connecta a un sòcol PAM del KWallet
Comment[es]=Conectar con el «socket» PAM de KWallet
Comment[nl]=Verbinden met KWallet PAM-socket
Comment[pt]=Ligar ao 'socket' de PAM do KWallet
Comment[pt_BR]=Conecta ao socket PAM do KWallet
Comment[sk]=Pripojiť na KWallet PAM socket
Comment[uk]=З’єднатися із сокетом PAM KWallet
Comment[x-test]=xxConnect to KWallet PAM socketxx
Exec=${CMAKE_INSTALL_FULL_LIBEXECDIR}/pam_kwallet_init
Type=Application
NoDisplay=true
X-KDE-StartupNotify=false
X-KDE-autostart-phase=0
