[Desktop Entry]
Name=KWallet PAM Socket Connection
Name[ca]=Connexió a sòcol PAM del KWallet
Name[ca@valencia]=Connexió a sòcol PAM del KWallet
Name[cs]=Připojení Socketu Kwallet PAM
Name[da]=KWallet PAM-sokkel-forbindelse
Name[de]=Verbindung zu KWallet-PAM-Socket
Name[el]=Σύνδεση υποδοχής KWallet PAM
Name[en_GB]=KWallet PAM Socket Connection
Name[es]=Conexión con el «socket» PAM de KWallet
Name[fi]=KWalletin PAM-pistokeyhteys
Name[gl]=Conexión ao sócket PAM de KWallet
Name[ko]=KWallet PAM 소켓 연결
Name[nl]=KWallet verbinding met PAM-socket
Name[nn]=KWallet PAM-socket-tilkopling
Name[pl]=Połączenie do gniazda PAM KPortfela
Name[pt]=Ligação por 'Socket' entre PAM e o KWallet
Name[pt_BR]=Conexão do Socket PAM do KWallet
Name[sk]=Pripojenie socketu KWallet PAM
Name[sl]=Povezava z vtičem PAM KWalleta
Name[sr]=Веза са К‑новчаниковим ПАМ сокетом
Name[sr@ijekavian]=Веза са К‑новчаниковим ПАМ сокетом
Name[sr@ijekavianlatin]=Veza sa K‑novčanikovim PAM soketom
Name[sr@latin]=Veza sa K‑novčanikovim PAM soketom
Name[sv]=Plånbokens PAM-uttagsanslutning
Name[uk]=З’єднання із сокетом PAM KWallet
Name[x-test]=xxKWallet PAM Socket Connectionxx
Name[zh_CN]=KWallet PAM 套接字连接
Comment=Connect to KWallet PAM socket
Comment[ca]=Connecta a un sòcol PAM del KWallet
Comment[ca@valencia]=Connecta a un sòcol PAM del KWallet
Comment[da]=Forbind til KWallet PAM-sokkel
Comment[de]=Zum KWallet-PAM-Socket verbinden
Comment[el]=Σύνδεση με υποδοχή KWallet PAM
Comment[en_GB]=Connect to KWallet PAM socket
Comment[es]=Conectar con el «socket» PAM de KWallet
Comment[fi]=Yhteys KWalletin PAM-pistokkeeseen
Comment[gl]=Conectar ao sócket PAM de KWallet
Comment[ko]=KWallet PAM 소켓에 연결할 수 없음
Comment[nl]=Verbinden met KWallet PAM-socket
Comment[nn]=Kopla til KWallet PAM-socket
Comment[pl]=Połącz z gniazdem PAM KPortfela
Comment[pt]=Ligar ao 'socket' de PAM do KWallet
Comment[pt_BR]=Conecta ao socket PAM do KWallet
Comment[sk]=Pripojiť na KWallet PAM socket
Comment[sl]=Povežite se z vtičem PAM KWalleta
Comment[sr]=Повежи се на К‑новчаников ПАМ сокет
Comment[sr@ijekavian]=Повежи се на К‑новчаников ПАМ сокет
Comment[sr@ijekavianlatin]=Poveži se na K‑novčanikov PAM soket
Comment[sr@latin]=Poveži se na K‑novčanikov PAM soket
Comment[sv]=Anslut till plånbokens PAM-uttag
Comment[uk]=З’єднатися із сокетом PAM KWallet
Comment[x-test]=xxConnect to KWallet PAM socketxx
Comment[zh_CN]=连接到 KWallet PAM 套接字
Exec=${CMAKE_INSTALL_FULL_LIBEXECDIR}/pam_kwallet_init
Type=Application
NoDisplay=true
X-KDE-StartupNotify=false
X-KDE-autostart-phase=0
